# Generated by Django 5.2.6 on 2025-09-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_apikey_options_alter_apikey_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='plain_suffix',
            field=models.TextField(blank=True, null=True),
        ),
    ]
